//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessia_2_PM_03
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonents
    {
        public string Номер_абонента { get; set; }
        public string ФИО { get; set; }
        public string Пол { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Номер_телефона { get; set; }
        public string Электронная_почта { get; set; }
        public string Адрес_прописки { get; set; }
        public string Адрес_проживания { get; set; }
        public string Серия_и_номер_паспорта { get; set; }
        public string Код_подразделения { get; set; }
        public string Кем_выдан { get; set; }
        public System.DateTime Дата_выдачи_паспорта { get; set; }
        public string Номер_договора { get; set; }
        public System.DateTime Дата_заключения_договора { get; set; }
        public string Тип_договора { get; set; }
        public string Причина_расторжения_договора { get; set; }
        public int Лицевой_счет { get; set; }
        public string Услуги { get; set; }
        public string Услуги2 { get; set; }
        public string Услуги3 { get; set; }
        public Nullable<System.DateTime> Дата_расторжения_договора { get; set; }
        public string column22 { get; set; }
        public string Серийный_номер_оборудования { get; set; }
    }
}
