//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace session_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class session2Entities : DbContext
    {
        private static session2Entities _context;
        public session2Entities()
        : base("name=session2Entities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static session2Entities GetContext()
        {
            if (_context == null)
                _context = new session2Entities();

            return _context;
        }
        
    
        public virtual DbSet<abonents> abonents { get; set; }
    }
}
